<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%
out.print("<chart caption='Site hits per hour' subCaption='In Thousands' numdivlines='9' lineThickness='2' showValues='0' numVDivLines='22' formatNumberScale='1' labelDisplay='ROTATE' slantLabels='1' anchorRadius='2' anchorBgAlpha='50' showAlternateVGridColor='1' anchorAlpha='100' animation='1' limitsDecimalPrecision='0' divLineDecimalPrecision='1'>");
out.print("<categories >");
out.print("<category label='00:00' />");
out.print("<category label='01:00' />");
out.print("<category label='02:00' />");
out.print("<category label='03:00' />");
out.print("<category label='04:00' />");
out.print("<category label='05:00' />");
out.print("<category label='06:00' />");
out.print("<category label='07:00' />");
out.print("<category label='08:00' />");
out.print("<category label='09:00' />");
out.print("<category label='10:00' />");
out.print("<category label='11:00' />");
out.print("<category label='12:00' />");
out.print("<category label='13:00' />");
out.print("<category label='14:00' />");
out.print("<category label='15:00' />");
out.print("<category label='16:00' />");
out.print("<category label='17:00' />");
out.print("<category label='18:00' />");
out.print("<category label='19:00' />");
out.print("<category label='20:00' />");
out.print("<category label='21:00' />");
out.print("<category label='22:00' />");
out.print("<category label='23:00' />");
out.print("</categories>");
out.print("<dataset seriesName='平台服务' color='808080' anchorBorderColor='808080'>");
out.print("<set value='37' link='n- falsh/xqlist.jsp' />");
out.print("<set value='45' />");
out.print("<set value='70' />");
out.print("<set value='79' />");
out.print("<set value='168' />");
out.print("<set value='337' />");
out.print("<set value='374' />");
out.print("<set value='431' />");
out.print("<set value='543' />");
out.print("<set value='784' />");
out.print("<set value='1117' />");
out.print("<set value='1415' />");
out.print("<set value='2077' />");
out.print("<set value='2510' />");
out.print("<set value='3025' />");
out.print("<set value='3383' />");
out.print("<set value='3711' />");
out.print("<set value='4016' />");
out.print("<set value='4355' />");
out.print("<set value='4751' />");
out.print("<set value='5154' />");
out.print("<set value='5475' />");
out.print("<set value='5696' />");
out.print("<set value='7801' />");
out.print("</dataset>");
out.print("<dataset seriesName='Tue' color='800080' anchorBorderColor='800080'>");
out.print("<set value='54' />");
out.print("<set value='165' />");
out.print("<set value='175' />");
out.print("<set value='190' />");
out.print("<set value='212' />");
out.print("<set value='241' />");
out.print("<set value='308' />");
out.print("<set value='401' />");
out.print("<set value='481' />");
out.print("<set value='851' />");
out.print("<set value='1250' />");
out.print("<set value='2415' />");
out.print("<set value='2886' />");
out.print("<set value='3252' />");
out.print("<set value='3673' />");
out.print("<set value='4026' />");
out.print("<set value='4470' />");
out.print("<set value='4813' />");
out.print("<set value='4961' />");
out.print("<set value='5086' />");
out.print("<set value='5284' />");
out.print("<set value='5391' />");
out.print("<set value='5657' />");
out.print("<set value='5847' />");
out.print("</dataset>");

out.print("</chart>");

%>
