// JavaScript Document
document.writeln("<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Transitional\/\/EN\" \"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-transitional.dtd\">");
document.writeln("<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\">");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\" \/>");
document.writeln("<script src=\"js\/jquery-1.8.3.js\"><\/script>");
document.writeln("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\" \/>  <!--自适应宽度,并不允许缩放-->");
document.writeln("<script mce_src=\"html:\/\/html5shim.googlecode.com\/svn\/trunk\/html5.js\"><\/script>");
document.writeln("<script src=\"http:\/\/html5media.googlecode.com\/svn\/trunk\/src\/html5media.min.js\"><\/script>");
document.writeln("<link rel=\"stylesheet\" href=\"css\/style.css\" \/>");
document.writeln("<\/head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<footer>");
document.writeln("		<ul>");
document.writeln("			<li>");
document.writeln("				<div><img src=\"images\/sy.png\"  width=\"20\" height=\"20\"\/><\/div>");
document.writeln("				<div style=\"margin-top:5px;\"><a href=\"index.html\">首页<\/a><\/div>");
document.writeln("			<\/li>");
document.writeln("			<li>");
document.writeln("				<div><img src=\"images\/yz.png\"  width=\"20\" height=\"20\"\/><\/div>");
document.writeln("				<div style=\"margin-top:5px;\"><a href=\"fenlei.html\">我的银座<\/a><\/div>");
document.writeln("			<\/li>");
document.writeln("			<li>");
document.writeln("				<div><img src=\"images\/shop.png\"  width=\"20\" height=\"20\"\/><\/div>");
document.writeln("				<div style=\"margin-top:5px;\"><a href=\"login.html\">购物车<\/a><\/div>");
document.writeln("			<\/li>");
document.writeln("			<li>");
document.writeln("				<div><img src=\"images\/ss.png\"  width=\"20\" height=\"20\"\/><\/div>");
document.writeln("				<div style=\"margin-top:5px;\"><a href=\"search.html\">搜索<\/a><\/div>");
document.writeln("			<\/li>");
document.writeln("			<li>");
document.writeln("				<div><img src=\"images\/more.png\"  width=\"20\" height=\"20\"\/><\/div>");
document.writeln("				<div style=\"margin-top:5px;\"><a href=\"all.html\">更多<\/a><\/div>");
document.writeln("			<\/li>");
document.writeln("		<\/ul>");
document.writeln("	<\/footer>");
document.writeln("<\/body>");
document.writeln("<\/html>");
document.writeln("")