 // JavaScript Document
document.writeln("<!DOCTYPE HTML>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\" \/>");
document.writeln("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\" \/>  <!--自适应宽度,并不允许缩放-->");
document.writeln("<script mce_src=\"html:\/\/html5shim.googlecode.com\/svn\/trunk\/html5.js\"><\/script>");
document.writeln("<script src=\"http:\/\/html5media.googlecode.com\/svn\/trunk\/src\/html5media.min.js\"><\/script>");
document.writeln("<link href=\"css\/index.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.writeln("<style>");
document.writeln("body{margin:0; padding:0;}");
document.writeln("a{color:#FFFFFF; text-decoration:none}");
document.writeln("header, footer, article, section, nav, menu, hgroup {display:block;}");
document.writeln("#list ul li{float:left; background:#e7e8ea; margin-top:10px;  width:48%; margin-left:5px;}");
document.writeln("#list ul li img{padding-left:5px;padding-right:5px; width:92%}");
document.writeln("footer{width:100%; margin:0 auto; color:#FFFFFF; font-size:12px; font-family:微软雅黑; background:#d9c0f9;height:40px; position:fixed; bottom:0;}");
document.writeln("footer ul{width:90%; margin:0 auto;}");
document.writeln("footer ul li{float:left;list-style:none; padding-top:10px; width:18%; margin-left:6px;}");
document.writeln("footer ul li a{color:#FFFFFF; text-decoration:none}");
document.writeln("<\/style>");
document.writeln("<\/head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<footer>");
document.writeln("	<ul>");
document.writeln("		<li>");
document.writeln("			<div><img src=\"images\/yuyue.png\"  width=\"15\" height=\"15\"\/><\/div>");
document.writeln("			<div><a href=\"index.html\">首页</a><\/div>");
document.writeln("		<\/li>");
document.writeln("		<li>");
document.writeln("			<div><img src=\"images\/phone.png\"  width=\"15\" height=\"15\"\/><\/div>");
document.writeln("			<div><a href=\"tel:123456789\">电话</a> <\/div>");
document.writeln("		<\/li>");
document.writeln("		<li>");
document.writeln("			<div><img src=\"images\/map.png\"  width=\"15\" height=\"15\"\/><\/div>");
document.writeln("			<div><a href=\"map.html\">地图</a><\/div>");
document.writeln("		<\/li>");
document.writeln("		<li>");
document.writeln("			<div><img src=\"images\/fenxiang.png\"  width=\"15\" height=\"15\"\/><\/div>");
document.writeln("			<div><a href=\"share.html\">分享</a><\/div>");
document.writeln("		<\/li>");
document.writeln("		<li>");
document.writeln("			<div><img src=\"images\/message.png\"  width=\"15\" height=\"15\"\/><\/div>");
document.writeln("			<div><a href=\"message.html\">留言</a><\/div>");
document.writeln("		<\/li>");
document.writeln("	<\/ul>");
document.writeln("<\/footer>");
document.writeln("<\/body>");
document.writeln("<\/html>");
document.writeln("")