document.writeln("<!DOCTYPE HTML>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\" \/>");
document.writeln("<link rel=\"stylesheet\" href=\"css\/m_style.css\"\/>");
document.writeln("<script type=\"text\/javascript\" src=\"js\/lib.min.js\"><\/script>");
document.writeln("<\/head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<header>");
document.writeln("	<img src=\"images\/logo.png\" \/>");
document.writeln("<\/header>");
document.writeln("<div id=\"box_root\" class =\"pageIndex\">");
document.writeln("<div id=\"box_mainBody\">");
document.writeln("<div id=\"box_main\" >");
document.writeln("<header id=\"box_header\" class=\"header\">");
document.writeln("<div class=\"columnSpace\" id=\"elem-navigation\" name=\"meun\"> ");
document.writeln("<div id=\"Columns_navigation\" class=\"Columns_navigation\">	");
document.writeln("<nav class=\"navigation01\" >");
document.writeln("<div class=\"navBarL active\" id=\"columnprev\" onClick=\"goPrev();\">				");
document.writeln("<span ><\/span><\/div>");
document.writeln("<div class=\"navBody\" id=\"singleScroll\">");
document.writeln("<ul class=\"sc_scroller\" id=\"singleScrollUl\" style=\"width:6000px\"><li><span class=\"active\" id=\"column1\"><a href=\"index.html\">首页<\/a><\/span><\/li><li><span class=\"active\" id=\"column2\"><a href=\"about.html\">关于我们<\/a><\/span><\/li><li><span class=\"active\" id=\"column3\"><a href=\"news.html\">作品展示<\/a><\/span><\/li><li><span class=\"active\" id=\"column4\"><a href=\"price.html\">拍摄报价<\/a><\/span><\/li><li><span class=\"active\" id=\"column5\"><a href=\"contant.html\">联系我们<\/a><\/span><\/li><\/ul>");
document.writeln("<\/div>");
document.writeln("<div class=\"navBarR active\" id=\"columnnext\" onClick=\"goNext();\">");
document.writeln("<span ><\/span><\/div>");
document.writeln("<\/nav>");
document.writeln("<script type=\"text\/javascript\">");
document.writeln("function setColumnWidth(){getTotalWidth(\'1\');getTotalWidth(\'2\');getTotalWidth(\'3\');getTotalWidth(\'4\');getTotalWidth(\'5\');$(\'#singleScrollUl\').css(\"width\",ulwidth);		");
document.writeln("}");
document.writeln("<\/script>");
document.writeln("");
document.writeln("<\/div> ");
document.writeln("<\/div>");
document.writeln("<\/header>");
document.writeln("");
document.writeln("﻿<\/div>");
document.writeln("<\/div>");
document.writeln("<\/div>");
document.writeln("<script type=\"text\/javascript\" src=\"http:\/\/js.s37.cn\/js\/qy_touch.js\"><\/script>");
document.writeln("<script type=\"text\/javascript\" src=\"http:\/\/js.s37.cn\/js\/m_common.js\"><\/script>");
document.writeln("");
document.writeln("<\/body>");
document.writeln("<\/html>");
document.writeln("")