package com.handany.bm.model;

import java.io.Serializable;

public class BmPicture implements Serializable {
	
	/**
	 * 压缩图片标记
	 */
	public static final String SMALL_IMG_FLAG="_small"; 
	
	private String lastOperator;
	
	private String realUrl;
	
	public String getLastOperator() {
		return lastOperator;
	}

	public void setLastOperator(String lastOperator) {
		this.lastOperator = lastOperator;
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Bm_Picture.id
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	private String id;		

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Bm_Picture.relate_id
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	private String relateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Bm_Picture.type
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Bm_Picture.url
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Bm_Picture.display_seq
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	private Integer displaySeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Bm_Picture.status
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Bm_Picture.last_modified
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	private String lastModified;
	
	private String header;
	
	private String descText;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Bm_Picture
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	private static final long serialVersionUID = 1L;	
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Bm_Picture.id
	 * @return  the value of Bm_Picture.id
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Bm_Picture.relate_id
	 * @return  the value of Bm_Picture.relate_id
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public String getRelateId() {
		return relateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Bm_Picture.relate_id
	 * @param relateId  the value for Bm_Picture.relate_id
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public void setRelateId(String relateId) {
		this.relateId = relateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Bm_Picture.type
	 * @return  the value of Bm_Picture.type
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Bm_Picture.type
	 * @param type  the value for Bm_Picture.type
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Bm_Picture.url
	 * @return  the value of Bm_Picture.url
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Bm_Picture.url
	 * @param url  the value for Bm_Picture.url
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Bm_Picture.display_seq
	 * @return  the value of Bm_Picture.display_seq
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public Integer getDisplaySeq() {
		return displaySeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Bm_Picture.display_seq
	 * @param displaySeq  the value for Bm_Picture.display_seq
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public void setDisplaySeq(Integer displaySeq) {
		this.displaySeq = displaySeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Bm_Picture.status
	 * @return  the value of Bm_Picture.status
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Bm_Picture.status
	 * @param status  the value for Bm_Picture.status
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Bm_Picture.last_modified
	 * @return  the value of Bm_Picture.last_modified
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public String getLastModified() {
		return lastModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Bm_Picture.last_modified
	 * @param lastModified  the value for Bm_Picture.last_modified
	 * @mbggenerated  Wed Jul 29 16:04:07 CST 2015
	 */
	public void setLastModified(String lastModified) {
		this.lastModified = lastModified;
	}
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getHeader() {
		return header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	public String getDescText() {
		return descText;
	}

	public void setDescText(String descText) {
		this.descText = descText;
	}

	public String getRealUrl() {
		return realUrl;
	}

	public void setRealUrl(String realUrl) {
		this.realUrl = realUrl;
	}
	
	
}