package com.handany.base.page;

import java.util.Date;

public class PageUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Pm_User.id
	 * @mbggenerated  Wed Jul 22 09:10:42 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Pm_User.login_name
	 * @mbggenerated  Wed Jul 22 09:10:42 CST 2015
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Pm_User.name
	 * @mbggenerated  Wed Jul 22 09:10:42 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Pm_User.brief_name
	 * @mbggenerated  Wed Jul 22 09:10:42 CST 2015
	 */
	private String briefName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Pm_User.password
	 * @mbggenerated  Wed Jul 22 09:10:42 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Pm_User.status
	 * @mbggenerated  Wed Jul 22 09:10:42 CST 2015
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Pm_User.last_modified
	 * @mbggenerated  Wed Jul 22 09:10:42 CST 2015
	 */
	private String lastModified;
	
	private int min;
	
	private int max;
	
	private String dateFrom;
	
	private String dateTo;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Pm_User
	 * @mbggenerated  Wed Jul 22 09:10:42 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBriefName() {
		return briefName;
	}

	public void setBriefName(String briefName) {
		this.briefName = briefName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getLastModified() {
		return lastModified;
	}

	public void setLastModified(String lastModified) {
		this.lastModified = lastModified;
	}

	public int getMin() {
		return min;
	}

	public void setMin(int min) {
		this.min = min;
	}

	public int getMax() {
		return max;
	}

	public void setMax(int max) {
		this.max = max;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getDateFrom() {
		return dateFrom;
	}

	public void setDateFrom(String dateFrom) {
		this.dateFrom = dateFrom;
	}

	public String getDateTo() {
		return dateTo;
	}

	public void setDateTo(String dateTo) {
		this.dateTo = dateTo;
	}



	
}
